export const formatEmployeePersonalInfomation = ({employeePersonalInfomation}) => {
  
  const {
    firstName,
    middleName,
    lastName,
    email,
    motherfirstName,
    fatherfirstName,
    nationality,
    dob,
    addrDoorNo,
    addrLine1,
    addrLine2,
    addrCityMandal,
    addrState,
    addrPincode = "",
    addrPermDoorNo = "",
    addrPermLine1 = "",
    addrPermLine2 = "",
    addrPermCityMandal = "",
    addrPermState = "",
    addrPermPincode = "",
    checkedPermAddress = false,
    mobileNumber = "8792795586",
    alternateNumber = "9686688659",
  } = employeePersonalInfomation;
  return {
    name: `${firstName} ${middleName || ""} ${lastName}`,
    email,
    "mother Name": motherfirstName,
    "father Name": fatherfirstName,
    nationality,
    "Date of Birth": dob,
    "Address Door No": addrDoorNo,
    addrLine1,
    addrLine2,
    addrCityMandal,
    addrState,
    addrPincode,
    addrPermDoorNo,
    addrPermLine1,
    addrPermLine2,
    addrPermCityMandal,
    addrPermState,
    addrPermPincode,
    checkedPermAddress,
    "mobile Number": mobileNumber,
    "alternate Number": alternateNumber,
  };
};
